### ISSUE TITLE
bug in write_ndArch header keyword removal

### ISSUE THREAD

**Issue by sbailey** [timahutchinson/redmonster#7]
`redmonster.datamgr.io2.write_ndArch` has some code like:

``` python
        try:
            hdr.remove('DUSTA')
        except ValueError:
            pass
```

It appears that this is a bug, at least with recent versions of astropy, which raise a `KeyError` instead of a `ValueError` in for this case.  e.g.

``` python
>>> from astropy.io import fits
>>> hdr = fits.Header()
>>> hdr.remove('BLAT')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sbailey/anaconda/lib/python2.7/site-packages/astropy/io/fits/header.py", line 1547, in remove
    raise KeyError("Keyword '%s' not found." % keyword)
KeyError: "Keyword 'BLAT' not found."
```

This was changed as part of PR #6 to bring in DESI changes (sorry...), and I think this was just an incorrect change.  I'm opening this issue because I don't know why we changed it in the first place, or whether it was leftover as a revert of a revert of a bug fix of a...  e.g. does some older version of astropy raise a ValueError or something?  Or should we just switch it back to catching a KeyError?

In particular, do you @timahutchinson have code to test whether `write_ndArch` still works before/after such a proposed change?

**Comment by timahutchinson** [comment]
I'm okay with changing it to a KeyError.  I made that change in a test copy of `write_ndArch` locally, and it works fine.

I'm not sure if older versions of astropy.io.fits used ValueError or not.  What about `except (KeyError, ValueError)`?  It might not look as nice, but it would work in the case of ValueError being raised.

**Comment by sbailey** [comment]
In general it is better to catch the minimal error possible such that you don't accidentally hide a different error.  Checking the astropy code history, it appears that it used to print a warning but not raise an error, and then it switched to raising a KeyError.  i.e. let's proceed with checking for KeyError.

Is your local copy in a state to merge that change into master, or would you like me to do it and submit a pull request?

**Comment by timahutchinson** [comment]
Sure. I'll just make the change in my master, and you can pull it into DESI.

**Comment by timahutchinson** [comment]
I made this change, so you can go ahead and pull.

**Comment by timahutchinson** [comment]
@sbailey Did this pull happen? I'd like to close to issue if possible.

**Comment by sbailey** [comment]
Yes, got it.  Thanks.  Closing ticket now.
